### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by fjlp** [kiwiz/gkeepapi#83]
Today was unable to use this API, it was working good yesterday:

```
Traceback (most recent call last):
  File "gg1.py", line 30, in <module>
    keep.resume('mymail@gmail.com', token1)
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gkeepapi\__init__.py", line 714, in resume
    self.load(auth, state, sync)
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gkeepapi\__init__.py", line 741, in load
    self.sync(True)
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gkeepapi\__init__.py", line 1016, in sync
    changes = self._keep_api.changes(
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gkeepapi\__init__.py", line 356, in changes
    return self.send(
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gkeepapi\__init__.py", line 221, in send
    response = self._send(**req_kwargs).json()
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\NEG\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gg1.py", line 43, in <module>
    print(e.raw)
AttributeError: 'JSONDecodeError' object has no attribute 'raw'
```

**Comment by ChocoTonic** [comment]
also having this issue

**Comment by tomerika** [comment]
Also having similar issue
I tried to switch into 2 factor authentication and use the "app password" instead of the password, but received the same error:

Traceback (most recent call last):
  File "/Users/tom/google-keep/env/googlekeepnotes", line 35, in <module>
    keep.resume("jackl56@gmail.com", token)
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 538, in resume
    self.load(auth, state, sync)
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 565, in load
    self.sync(True)
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 825, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 331, in changes
    json=params
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 205, in send
    response = self._send(**req_kwargs).json()
  File "/Users/tom/google-keep/env/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ChocoTonic** [comment]
> 
> 
> Also having similar issue
> I tried to switch into 2 factor authentication and use the "app password" instead of the password, but received the same error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/tom/google-keep/env/googlekeepnotes", line 35, in <module>
>     keep.resume(username, token)
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 538, in resume
>     self.load(auth, state, sync)
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 565, in load
>     self.sync(True)
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 825, in sync
>     labels=[i.save() for i in self._labels.values()] if labels_updated else None,
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 331, in changes
>     json=params
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/gkeepapi/__init__.py", line 205, in send
>     response = self._send(**req_kwargs).json()
>   File "/Users/tom/google-keep/env/lib/python3.7/site-packages/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

I had already changed over to 2FA and used an application password to get this API to work for me. how did you get it to work without the application password?

**Comment by tomerika** [comment]
I get the same error with both ways (JSONDecodeError)

**Comment by fjlp** [comment]
Is retrieving error code 403

https://www.googleapis.com:443 "POST /notes/v1/changes HTTP/1.1" 403 1103

**Comment by jo-naka** [comment]
I've been there.
I changed the app password, but that didn't resolve the error.
```
Traceback (most recent call last):
  File "sample.py", line 45, in <module>
    keep = keeplogin()
  File "sample.py", line 18, in keeplogin
    s = keep.login(userID,Password)
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\gkeepapi\__init__.py", line 695, in login
    self.load(auth, state, sync)
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\gkeepapi\__init__.py", line 741, in load
    self.sync(True)
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\gkeepapi\__init__.py", line 1016, in sync
    changes = self._keep_api.changes(
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\gkeepapi\__init__.py", line 356, in changes
    return self.send(
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\gkeepapi\__init__.py", line 221, in send
    response = self._send(**req_kwargs).json()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mjcatanz** [comment]
Same error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" as those above. Was working fine yesterday. I can paste the error message, but its the same as ChocoTonic, jo-naka, and tomerika. I'm using an app password.

**Comment by Stefan-Markus** [comment]
I'm getting the same error: `JSONDecodeError: Expecting value: line 1 column 1 (char 0)
` 
It was working on Tuesday, May 5th and then I tried running my script the next evening as usual and got an error that I eventually figured out was due to not being able to login. One thing I think might be helpful in figuring out the issue is that **I don't get the error if I set sync=False**, so the issue might be with syncing. Here's the full error message I get when trying to sync (very similar to everyone else, except I was testing it using Jupyter Notebooks and Anaconda3):
`JSONDecodeError                           Traceback (most recent call last)
<ipython-input-31-55826f1eef2e> in <module>
----> 1 keep.sync()

~\Anaconda3\lib\site-packages\gkeepapi\__init__.py in sync(self, resync)
    871                 target_version=self._keep_version,
    872                 nodes=[i.save() for i in self._findDirtyNodes()],
--> 873                 labels=[i.save() for i in self._labels.values()] if labels_updated else None,
    874             )
    875 

~\Anaconda3\lib\site-packages\gkeepapi\__init__.py in changes(self, target_version, nodes, labels)
    356             url=self._base_url + 'changes',
    357             method='POST',
--> 358             json=params
    359         )
    360 

~\Anaconda3\lib\site-packages\gkeepapi\__init__.py in send(self, **req_kwargs)
    218         while True:
    219             # Send off the request. If there was no error, we're good.
--> 220             response = self._send(**req_kwargs).json()
    221             if 'error' not in response:
    222                 break

~\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~\Anaconda3\lib\site-packages\simplejson\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    523             parse_constant is None and object_pairs_hook is None
    524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
    526     if cls is None:
    527         cls = JSONDecoder

~\Anaconda3\lib\site-packages\simplejson\decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~\Anaconda3\lib\site-packages\simplejson\decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

~\Anaconda3\lib\site-packages\simplejson\scanner.py in scan_once(string, idx)
     77             raise JSONDecodeError('Expecting value', string, idx)
     78         try:
---> 79             return _scan_once(string, idx)
     80         finally:
     81             memo.clear()

~\Anaconda3\lib\site-packages\simplejson\scanner.py in _scan_once(string, idx)
     68             return parse_constant('-Infinity'), idx + 9
     69         else:
---> 70             raise JSONDecodeError(errmsg, string, idx)
     71 
     72     def scan_once(string, idx):

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by fjlp** [comment]
Here is the debug logs from POST request, there is a HTTP Status Code 403

``` 
07/05/2020 02:55:44 PM Loading KWallet
07/05/2020 02:55:44 PM Loading SecretService
07/05/2020 02:55:44 PM Loading Windows
07/05/2020 02:55:44 PM Loading chainer
07/05/2020 02:55:44 PM Loading macOS
07/05/2020 02:55:44 PM <gkeepapi.Keep object at 0x00EB8160>
07/05/2020 02:55:44 PM Starting new HTTPS connection (1): android.clients.google.com:443
07/05/2020 02:55:44 PM https://android.clients.google.com:443 "POST /auth HTTP/1.1" 200 None
07/05/2020 02:55:44 PM Starting new HTTPS connection (1): android.clients.google.com:443
07/05/2020 02:55:45 PM https://android.clients.google.com:443 "POST /auth HTTP/1.1" 200 None
07/05/2020 02:55:45 PM Starting reminder sync: None
07/05/2020 02:55:45 PM Starting new HTTPS connection (1): www.googleapis.com:443
07/05/2020 02:55:47 PM https://www.googleapis.com:443 "POST /reminders/v1internal/reminders/list HTTP/1.1" 200 None
07/05/2020 02:55:47 PM Finishing sync: 0
07/05/2020 02:55:47 PM https://www.googleapis.com:443 "POST /reminders/v1internal/reminders/history HTTP/1.1" 200 None
07/05/2020 02:55:47 PM Starting keep sync: None
07/05/2020 02:55:47 PM Syncing 0 labels and 0 nodes
07/05/2020 02:55:47 PM Starting new HTTPS connection (1): www.googleapis.com:443
07/05/2020 02:55:48 PM https://www.googleapis.com:443 "POST /notes/v1/changes HTTP/1.1" 403 1103
```

When executing
```
return self.send(
            url=self._base_url + 'changes',
            method='POST',
            json=params
        )
```
from
`def changes(self, target_version=None, nodes=None, labels=None):` 

Could be that the url for http POST has been changed?

**Comment by kiwiz** [comment]
Looks like Google is explicitly requests with `gkeepapi` in the User-Agent. Changing it to any other value works fine. Not sure how I want to proceed here - this could become a tedious cat & mouse game. In the meantime, if you want to fix this yourself you can update line 184 in `__init__.py`.

**Comment by fjlp** [comment]
That works!
Its posible that google blocks any other request with a common User-Agent?

**Comment by Stefan-Markus** [comment]
That solved it for me. Maybe you need to make the user-agent a randomized string ;)

**Comment by kiwiz** [comment]
Looks like the match pattern is `^gkeepapi`. I'm going to work around it for now. Maybe someone from Google will pop by with more information :shrug:

**Comment by ChocoTonic** [comment]
what do you all use the API for? @fjlp @mjcatanz @tomerika @Stefan-Markus

**Comment by Stefan-Markus** [comment]
> what do you all use the API for? @fjlp @mjcatanz @tomerika @Stefan-Markus 
I just use it to create and label a To-Do list every night for the next day. You think someone is using it for something that triggered an API-wide block from Google?

**Comment by wizpig64** [comment]
I too am simply automating the boring parts of my daily todo lists, running once every 24 hours. The idea that Google would decide to block fellow developers from having any fun with their own kept notes is pretty concerning.

**Comment by jason79** [comment]
I listen to conference calls all day and at the end the script puts the calls in the right folders. Probably saves me at 20 minutes everyday.

**Comment by jason79** [comment]
i don't understand why Google is blocking it. Either they themselves should come out with an API for Keep which I think everybody has been asking for, or don't mess with things that are already built that people find useful. WTF google?
